AuthSystem/Models/Courier.cs
using AuthSystem.Controllers;
using Microsoft.AspNetCore.Components;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AuthSystem.Models
{
    
    public class Courier
    {
        // And if you want a brand new Guid then just do

        private Guid uid = Guid.NewGuid();
        
        // If you already have a string representation of the Guid, you can do this:

        Guid guid = new Guid("11223344-5566-7788-99AA-BBCCDDEEFF00");

        

        /*public DateTime GetDateTime { get; set; }

        private Guid guid;

        public Courier(Guid guid)
        {
            this.guid = guid;
        }

        public Guid GetGuid()
        {
            return guid;
        }

        public void SetGuid(Guid value)
        {
            string guid = Guid.NewGuid().ToString().Replace("-", "").ToUpper();
        }*/
    }
}

AuthSystem/Controllers/CourierController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.IdentityModel.Tokens;

namespace AuthSystem.Controllers
{
    [Authorize]
    public class CourierController : Controller
    {
        public IActionResult DateTime()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Select()
        {
            return View();
        }

        public IActionResult Generate(string productId)
        {
            ViewBag.productId = productId;
            return View("Index");
        }
    }

}

AuthSystem/Views/Courier/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@*function func() {
        var d = new Date().getTime().toString();
        document.write(d);
    }*@

<!----<style>

    button {
        background-color: #54fdae;
        padding: 5px;
        margin: 10px;
        border: 0;
        border-radius: 3px;
        outline: 0;
        cursor: pointer;
    }

        button:hover {
            background-color: #32ee9a;
        }

    input {
        border: 0;
        border-bottom: 1px solid #000;
        padding: 3px;
        margin: 10px;
        outline: 0;
    }
</style>---->

<script>
    function uuid() {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
            var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
        });
    }

    var userID = uuid();//something like: "ec0c22fa-f909-48da-92cb-db17ecdb91c5"

    function func() {
        var d = new Date().getTime().toString();
        document.write(d);
    }

</script>

<!---

@*<button id="generateID">Generate ID</button>
<input type="text" id="generateidtxt" />
<br />
<input type="submit" value="DatTime" onclick="getElementById('d')" />
<input type="text" placeholder="ProductId" name="ProductId" id="d" />*@



@*Following button gives random uuid*@-->



<!---Click button to generate UUID and then copy the --->

<button class="btn btn-primary" id="button" onclick="getElementById('random-number').value = new Date().getTime().toString()">Create Random Number</button>
<br>
<input id="random-number" value="" />



<form method="post" asp-controller="Courier" asp-action="generate">


    <input type="text" placeholder="productId" name="productId" />
    <input type="submit" value="Generate" />
</form>

@if (ViewBag.productId != null)
{
    <qrcode content="@ViewBag.productId" width="200" height="200" alt="" name="productId" />
    <barcode content="@ViewBag.productId" width="500" height="50" alt="" name="productId" />
}

AuthSystem/Views/Courier/Select.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



<a asp-action="Index" class="btn btn-primary">Courier</a>
<a asp-action="Index" class="btn btn-primary">Company Mail</a>